add_newline = false

[character]
success_symbol = "âœ"
error_symbol = "âœ"

[python]
symbol = "ğŸ "
format = "via [$symbol$version]($style) "

[git_branch]
symbol = "ğŸŒ± "
format = "on [$symbol$branch]($style) "

[directory]
truncation_length = 3
truncate_to_repo = true
